# -*- coding: utf-8 -*-
"""data-visulization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Gauravi-Ubhare/cefa88a28146238d936401df49d62e53/data-visulization.ipynb
"""

from google.colab import drive
drive.mount("/content/drive")

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/brain_stroke.csv')
df

df.shape

df.isnull()

df.info()

df.nunique()

df.describe()

df['smoking_status'].value_counts()

df['avg_glucose_level'].value_counts()

df['work_type'].value_counts()

df['Residence_type'].value_counts()

df['gender'].value_counts()

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

plt.figure(figsize=(10, 6))
plt.subplot(2, 2, 1)
sns.boxplot(y='avg_glucose_level', data=df)
plt.title('Boxplot of avg_glucose_level')
plt.subplot(2, 2, 2)
sns.boxplot(y='age', data=df)
plt.title('Boxplot of age')
plt.tight_layout()
plt.show()

sns.histplot(data=df, x='bmi', bins=6, kde=True, color='green',edgecolor='blue')
plt.xlabel('Bmi')
plt.ylabel('Frequency')
plt.show()

gender_distribution=df['gender'].value_counts()
gender_distribution.plot(kind='pie',autopct='%1.1f%%')
plt.title('Gender Distribution')
plt.show()

plt.figure(figsize=(6,7))
sns.histplot(data=df, x='age',bins=20, kde=True, color='red',edgecolor='blue')
plt.title('Frequency of age')
plt.xlabel("Age")
plt.ylabel('Frequency')
plt.show()

#which one have lowest smoking_status?
import matplotlib.pyplot as plt
import pandas as pd
data = {'smoking_status': ['never smoked', 'unknown', 'formerly smoked', 'smokes'],
        'count': [1838,1500,867,776]}
df = pd.DataFrame(data)
e=[0.0,0.0,0.0,0.3]
colors = ['coral', 'blue', 'green', 'skyblue']
plt.figure(figsize=(6, 6))
plt.pie(df['count'], labels=df['smoking_status'], colors=colors, autopct='%1.1f%%', startangle=140, explode=e)
plt.title('Smoking Status Distribution')
plt.axis('equal')
plt.show()

corr_matrix=df[['stroke','bmi','heart_disease','hypertension']]
corr_data=corr_matrix.corr()
plt.figure(figsize=(6,6),dpi=100)
sns.heatmap(corr_data, annot=True, cmap='flare',fmt=".2f")
plt.title("correlation matrix heatmap")
plt.show()

plt.figure(figsize=(6,5))
sns.violinplot(data=df, x='work_type',y='bmi',hue='gender',palette="husl")
plt.xlabel('Wrok type')
plt.ylabel('Bmi')
plt.xticks(rotation=0)
plt.legend(loc='upper left',ncol=2)
plt.show()

plt.figure(figsize=(6,6))
sns.scatterplot(data=df, x='smoking_status',y='age',color='orange')
plt.title("Smoking satuts ")
plt.xlabel("Smoking_status")
plt.ylabel("Age")
plt.show()

br=df['Residence_type'].sort_values(ascending=True)
plt.figure(figsize=(6,6))
sns.barplot(x=br, y='avg_glucose_level', hue='gender',data=df,errorbar=None, palette='Set1')
plt.xlabel('Residence type')
plt.ylabel('Avg_glucose level')
plt.title("Avg_glucose level in Male and Female")
plt.legend(loc='upper center',ncol=2)
plt.show()

sns.pairplot(df[['hypertension',	'heart_disease','stroke']], diag_kind='kde')
plt.suptitle("Pair Plot of Disease", y=1.01)
plt.show()

sns.countplot(x=df['Residence_type'])

df.boxplot(column=['bmi'])
plt.show()

plt.figure(figsize=(6,6))
sns.countplot(x='smoking_status',data=df,palette='rocket_r',order=df['smoking_status'].value_counts().index)
plt.xticks(rotation=0)
plt.show()

sns.lineplot(x='smoking_status',y='avg_glucose_level',label='Smoking Status',data=df)
plt.legend()
plt.show()